# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('university', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='founder',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BP.Posting'),
        ),
    ]
