# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_text',
            field=models.CharField(default='Help with public relations', max_length=200),
            preserve_default=False,
        ),
    ]
