# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0005_auto_20170430_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='display_in_directory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_in_directory',
            field=models.BooleanField(default=False),
        ),
    ]
