# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0006_auto_20170501_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='display_in_directory',
            new_name='display_in_company_directory',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_in_directory',
            new_name='interested_in_joining_a_startup',
        ),
    ]
