# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0007_auto_20170501_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50),
        )
    ]
