# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0010_auto_20170501_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='pay',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
